### ISSUE TITLE
Allow for disabling colors in log output

### ISSUE THREAD

**Issue by rtyler** [xvxx/phd#2]
Since `phd` is logging to syslog, the color codes being inserted into the log stream make things very difficult.

I can probably submit a pull request to change this, but to do it sanely, I believe I would want to replace `src/colors.rs` with https://github.com/ogham/rust-ansi-term and perhaps do some refactoring to allow for color toggling.at runtime.

Are you particularly partial to how colors are logged, or would pretty_env_logger be sufficient for you?

**Comment by xvxx** [comment]
I added a `--no-color` command line flag in 4ee7008070560b16fd7f10745c67a0a1d38d83e4. Does that work for you? I am open to other flag names, too.

I would prefer to keep the dependency count as low as possible, I'm pretty grumpy about compile times. Even if that means going with a less-than-sane approach to doing things.

**Comment by rtyler** [comment]
I'll test it later but looks good to me
